global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-dubbo-consumer'
    static_configs:
      - targets: ['192.168.1.52:39154']
    metrics_path: "/actuator/prometheus"
  - job_name: 'spring-dubbo-provider'
    static_configs:
      - targets: ['192.168.1.52:39155']
    metrics_path: "/actuator/prometheus"
